# -*- coding: utf-8 -*-
"""Diabetes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M6JLr6W0RgNcutFEcleGpX173QaAMaaa
"""

import pandas as pd
df=pd.read_csv('diabetes.csv')

df.isnull().sum()

x=df.drop(['Outcome'],axis=1)

y=df['Outcome']

import seaborn as sns
sns.countplot(x=y)

y.value_counts()

from sklearn.preprocessing import MinMaxScaler

scaler=MinMaxScaler()

x_scaled=scaler.fit_transform(x)

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x_scaled,y,random_state=0,test_size=0.2)

from sklearn.neighbors import KNeighborsClassifier

knn=KNeighborsClassifier()

knn.fit(x_train,y_train)

y_pred=knn.predict(x_test)

from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, accuracy_score
print("Confusion Matrix")
print(confusion_matrix(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))
print("Reacal Score:", recall_score(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred))
print("Precision Score:",precision_score(y_test, y_pred))